import React, { useState, useEffect } from 'react';
import { View, Text, FlatList } from 'react-native';
import database from '@react-native-firebase/database';
import AsyncStorage from '@react-native-async-storage/async-storage';

const MyGB = () => {
  const [greatBuildings, setGreatBuildings] = useState([]);
    const [error, setError] = useState(null);

      useEffect(() => {
          const fetchGreatBuildings = async () => {
                try {
                        console.log('Fetching guildId and userId from AsyncStorage...');
                                const guildId = await AsyncStorage.getItem('guildId');
                                        const userId = await AsyncStorage.getItem('userId');
                                                console.log('guildId:', guildId);
                                                        console.log('userId:', userId);

                                                                if (guildId && userId) {
                                                                          const userRef = database().ref(`guilds/${guildId}/guildUsers/${userId}/greatBuild`);
                                                                                    console.log(`Fetching data from path: guilds/${guildId}/guildUsers/${userId}/greatBuild`);

                                                                                              userRef.once('value', (snapshot) => {
                                                                                                          if (snapshot.exists()) {
                                                                                                                        const buildingsData = snapshot.val();
                                                                                                                                      console.log('Data fetched from Firebase:', buildingsData);

                                                                                                                                                    const buildingsArray = Object.entries(buildingsData);
                                                                                                                                                                  setGreatBuildings(buildingsArray);
                                                                                                                                                                                console.log('Formatted data for FlatList:', buildingsArray);
                                                                                                                                                                                            } else {
                                                                                                                                                                                                          setError('Дані користувача не знайдено');
                                                                                                                                                                                                                        console.error('No data found for the user in Firebase.');
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                setError('guildId або userId не знайдено в AsyncStorage');
                                                                                                                                                                                                                                                                          console.error('guildId або userId не знайдено в AsyncStorage');
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                setError(`Помилка при отриманні даних: ${error.message}`);
                                                                                                                                                                                                                                                                                                        console.error('Error fetching data:', error);
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                      fetchGreatBuildings();
                                                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                                                          if (error) {
                                                                                                                                                                                                                                                                                                                              console.log('Error encountered:', error);
                                                                                                                                                                                                                                                                                                                                  return <Text>{error}</Text>;
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                          <FlatList
                                                                                                                                                                                                                                                                                                                                                data={greatBuildings}
                                                                                                                                                                                                                                                                                                                                                      keyExtractor={(item) => item[0]}
                                                                                                                                                                                                                                                                                                                                                            renderItem={({ item }) => (
                                                                                                                                                                                                                                                                                                                                                                    <View style={{ padding: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                              <Text>Будівля: {item[0]}</Text>
                                                                                                                                                                                                                                                                                                                                                                                        <Text>Рівень: {item[1].level}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                  <Text>Інвестори: {item[1].investors ? JSON.stringify(item[1].investors) : 'Немає даних'}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                      export default MyGB;
                                                                                                                                                                                                                                                                                                                                                                                                                    