import React, { useState, useEffect } from 'react';
import { View, Text, FlatList, StyleSheet, TextInput, Button } from 'react-native';
import { getDatabase, ref, onValue, push, set } from 'firebase/database';
import AsyncStorage from '@react-native-async-storage/async-storage';

const ChatWindow = ({ route, navigation }) => {
  const [messages, setMessages] = useState([]);
    const [newMessage, setNewMessage] = useState('');
      const { chatId, initialMessage, isGroupChat } = route.params || {};
        const [userId, setUserId] = useState(null);
          const [guildId, setGuildId] = useState(null);

            // Fetching userId and guildId from AsyncStorage
              useEffect(() => {
                  const fetchUserIdAndGuildId = async () => {
                        try {
                                const storedUserId = await AsyncStorage.getItem('userId');
                                        const storedGuildId = await AsyncStorage.getItem('guildId');
                                                console.log('User ID from AsyncStorage:', storedUserId);
                                                        console.log('Guild ID from AsyncStorage:', storedGuildId);
                                                                setUserId(storedUserId);
                                                                        setGuildId(storedGuildId);
                                                                              } catch (error) {
                                                                                      console.error('Error fetching user or guild ID: ', error);
                                                                                            }
                                                                                                };

                                                                                                    fetchUserIdAndGuildId();
                                                                                                      }, []);

                                                                                                        // Fetching chat name from Firebase and setting navigation title
                                                                                                          useEffect(() => {
                                                                                                              console.log('Chat ID:', chatId);
                                                                                                                  console.log('Guild ID:', guildId);

                                                                                                                      if (chatId && guildId) {
                                                                                                                            const db = getDatabase();
                                                                                                                                  const chatRef = ref(db, `guilds/${guildId}/chats/${chatId}/name`);

                                                                                                                                        console.log('Fetching chat name from Firebase...');

                                                                                                                                              onValue(chatRef, (snapshot) => {
                                                                                                                                                      const chatName = snapshot.val();
                                                                                                                                                              console.log('Chat Name from Firebase:', chatName);

                                                                                                                                                                      if (chatName) {
                                                                                                                                                                                navigation.setOptions({ 
                                                                                                                                                                                            title: isGroupChat ? chatName : `Chat with ${chatName}`,
                                                                                                                                                                                                      });
                                                                                                                                                                                                              }
                                                                                                                                                                                                                    });
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                          }, [chatId, guildId, isGroupChat, navigation]);

                                                                                                                                                                                                                            // Fetching chat messages from Firebase
                                                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                                                  const fetchMessages = () => {
                                                                                                                                                                                                                                        if (!chatId || !guildId) return;

                                                                                                                                                                                                                                              console.log('Fetching messages from Firebase...');

                                                                                                                                                                                                                                                    const db = getDatabase();
                                                                                                                                                                                                                                                          const messagesRef = ref(db, `guilds/${guildId}/chats/${chatId}/messages`);

                                                                                                                                                                                                                                                                onValue(messagesRef, (snapshot) => {
                                                                                                                                                                                                                                                                        const messagesData = snapshot.val() || {};
                                                                                                                                                                                                                                                                                const messagesList = Object.keys(messagesData).map((key) => ({
                                                                                                                                                                                                                                                                                          id: key,
                                                                                                                                                                                                                                                                                                    ...messagesData[key],
                                                                                                                                                                                                                                                                                                            }));
                                                                                                                                                                                                                                                                                                                    console.log('Messages from Firebase:', messagesList);
                                                                                                                                                                                                                                                                                                                            setMessages(messagesList);
                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                          fetchMessages();
                                                                                                                                                                                                                                                                                                                                            }, [chatId, guildId]);

                                                                                                                                                                                                                                                                                                                                              // Sending the initial message if provided
                                                                                                                                                                                                                                                                                                                                                useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                    console.log('Initial message:', initialMessage);
                                                                                                                                                                                                                                                                                                                                                        if (initialMessage) {
                                                                                                                                                                                                                                                                                                                                                              handleSendMessage(); // Send the initial message if needed
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                    }, [initialMessage]);

                                                                                                                                                                                                                                                                                                                                                                      // Function to handle sending new messages
                                                                                                                                                                                                                                                                                                                                                                        const handleSendMessage = async () => {
                                                                                                                                                                                                                                                                                                                                                                            if (newMessage.trim() === '') return;

                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                      const db = getDatabase();
                                                                                                                                                                                                                                                                                                                                                                                            if (!chatId || !userId || !guildId) throw new Error('Missing IDs');

                                                                                                                                                                                                                                                                                                                                                                                                  const messageRef = ref(db, `guilds/${guildId}/chats/${chatId}/messages`);
                                                                                                                                                                                                                                                                                                                                                                                                        const newMessageRef = push(messageRef);

                                                                                                                                                                                                                                                                                                                                                                                                              await set(newMessageRef, {
                                                                                                                                                                                                                                                                                                                                                                                                                      senderId: userId,
                                                                                                                                                                                                                                                                                                                                                                                                                              text: newMessage,
                                                                                                                                                                                                                                                                                                                                                                                                                                      timestamp: Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log('Message sent:', newMessage);

                                                                                                                                                                                                                                                                                                                                                                                                                                                        setNewMessage('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error('Error sending message: ', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const renderItem = ({ item }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <View style={[styles.messageContainer, item.senderId === userId ? styles.myMessage : styles.theirMessage]}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.messageText}>{item.text}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <View style={styles.container}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <FlatList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              data={messages}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      renderItem={renderItem}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              keyExtractor={(item) => item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={styles.messagesList}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <View style={styles.inputContainer}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <TextInput
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={newMessage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChangeText={setNewMessage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Write a message..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button title="Send" onPress={handleSendMessage} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                messagesList: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        paddingHorizontal: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            messageContainer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginVertical: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            maxWidth: '80%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                myMessage: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alignSelf: 'flex-end',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#DCF8C6',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            theirMessage: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alignSelf: 'flex-start',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: '#ECECEC',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        messageText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                inputContainer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderTopWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderTopColor: '#ddd',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderColor: '#ddd',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        paddingHorizontal: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            paddingVertical: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default ChatWindow;